name: Compile PDF Document

on:
  push:
    branches:
      - 'main'

jobs:
  # Job #1 - Generate an embedded SVG asset, showing all contributors
  compile-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Make PDF 
        uses: baileyjm02/markdown-to-pdf@v1.1.0
        with:
          input_dir: .
          output_dir: .github/assets/
          build_pdf: true
          build_html: false
          table_of_contents: false
      - name: Upload Artifact 
        uses: actions/upload-artifact@v3.1.1
        with:
          name: awesome-information-pdf
          path: .github/assets/README.pdf
      - name: Commit file 
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Create PDF
          branch: main
          commit_user_name: GitHub Bot
          commit_user_email: actions@github.com
          commit_author: action
      - name: Push changes 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}